//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBootstrapDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public int TabID { get; set; }
        public int ParentID { get; set; }
        public int RoleID { get; set; }
        public string Title { get; set; }
        public string PageIcon { get; set; }
        public string URL { get; set; }
        public bool IsDropDown { get; set; }
        public bool IsActive { get; set; }
        public string JobID { get; set; }
        public Nullable<byte> Ordering { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
